language: node_js
node_js:
  - "10"

install: 
  - npm install -g @argdown/cli
  
script:
  - argdown map --format svg abortion.argdown out
  - argdown html abortion.argdown
  - mv html/argdown.css out/argdown.css
  - cat html/top.html > out/index.html
  - cat out/abortion.html >> out/index.html
  - cat html/bottom.html >> out/index.html

deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  on:
    branch: master
